[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    --verbose
    --html=reports/report.html
    --self-contained-html

markers =
    smoke: Tests críticos que deben pasar siempre
    regression: Tests de regresión completos
    login: Tests relacionados con login
    cart: Tests relacionados con carrito
    checkout: Tests relacionados con checkout
    slow: Tests que tardan más de 10 segundos

log_cli = true
log_cli_level = INFO