[pytest]
# Carpeta donde están los tests
testpaths = selenium-python-project/tests

# Formato de los nombres de tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones por defecto al correr pytest
addopts = 
    --verbose
    --html=selenium-python-project/reports/report.html
    --self-contained-html

# Mostrar prints en consola
log_cli = true
log_cli_level = INFO